# Default values for voyagelab Helm chart
global:
  environment: development
  # Set to "gcr.io/YOUR-PROJECT-ID" for GCP deployment
  registry: "localhost:5110"
  enableNodePort: false
  enableLoadBalancer: true

brainApi:
  name: brain-api
  image:
    repository: "vl/brain-api"
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    containerPort: 3000
    port: 3090
    nodePort: 32001
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

brainUi:
  name: brain-ui
  image:
    repository: "vl/brain-ui"
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    containerPort: 80
    port: 8090
    nodePort: 32002
  resources:
    limits:
      cpu: 300m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  config:
    apiUrl: http://localhost:3090