apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-brain-api
  labels:
    {{- include "voyagelab.labels" . | nindent 4 }}
    app.kubernetes.io/component: brain-api
spec:
  type: {{ if .Values.global.enableLoadBalancer }}LoadBalancer{{ else if .Values.global.enableNodePort }}NodePort{{ else }}ClusterIP{{ end }}
  ports:
    - protocol: TCP
      port: {{ .Values.brainApi.service.port }}
      targetPort: {{ .Values.brainApi.service.containerPort }}
      name: http
      {{- if .Values.global.enableNodePort }}
      nodePort: {{ .Values.brainApi.service.nodePort }}
      {{- end }}
  selector:
    {{- include "voyagelab.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: brain-api