apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-brain-api
  labels:
    {{- include "voyagelab.labels" . | nindent 4 }}
    app.kubernetes.io/component: brain-api
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "voyagelab.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: brain-api
  template:
    metadata:
      labels:
        {{- include "voyagelab.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: brain-api
    spec:
      containers:
        - name: {{ .Values.brainApi.name }}
          image: "{{ .Values.global.registry }}/{{ .Values.brainApi.image.repository }}:{{ .Values.brainApi.image.tag }}"
          imagePullPolicy: {{ .Values.brainApi.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.brainApi.service.port }}
              protocol: TCP
          env:
            - name: NODE_ENV
              value: {{ .Values.global.environment }}
            - name: CORS_ORIGIN
              value: {{ .Values.global.corsOrigin }}
          resources:
            {{- toYaml .Values.brainApi.resources | nindent 12 }}