apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-brain-api
  labels:
    {{- include "voyagelab.labels" . | nindent 4 }}
    app.kubernetes.io/component: brain-api
spec:
  # type: {{ .Values.brainApi.service.type }}
  type: {{ if .Values.brainApi.service.enableNodePort }}NodePort{{ else }}ClusterIP{{ end }}
  ports:
    - protocol: TCP
      port: {{ .Values.brainApi.service.port }}
      targetPort: 3000
      name: http
      {{- if .Values.brainApi.service.enableNodePort }}
      nodePort: {{ .Values.brainApi.service.nodePort }}
      {{- end }}
  selector:
    {{- include "voyagelab.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: brain-api