apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-brain-ui
  labels:
    {{- include "voyagelab.labels" . | nindent 4 }}
    app.kubernetes.io/component: brain-ui
spec:
  type: {{ if .Values.global.enableLoadBalancer }}LoadBalancer{{ else if .Values.global.enableNodePort }}NodePort{{ else }}ClusterIP{{ end }}
  ports:
    - port: {{ .Values.brainUi.service.port }}
      targetPort: {{ .Values.brainUi.service.containerPort }}
      {{- if .Values.global.enableNodePort }}
      nodePort: {{ .Values.brainUi.service.nodePort }}
      {{- end }}
  selector:
    {{- include "voyagelab.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: brain-ui